target 'dataFetchingTest' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for dataFetchingTest

pod 'MBProgressHUD'
pod 'UICKeyChainStore'
pod 'AFNetworking'
pod 'FMDB'

end


